import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.scss";
import Header from "@/widgets/header/Header";
import Footer from "@/widgets/footer/Footer";

const cannonade = localFont({
  src: [
    {
      path: "../public/fonts/Cannonade Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/fonts/Cannonade.ttf",
      weight: "500",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="initial-scale=1, width=device-width" />
      </head>
      <body className={`${cannonade.className} antialiased`}>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
